### ISSUE TITLE
Hi, is there any way to restore m2 to parallel data?

### ISSUE THREAD

**Issue by hqsiswiliam** [chrisjbryant/errant#13]

**Comment by hqsiswiliam** [comment]
I have written the generation code by myself.

**Comment by Chhokra** [comment]
> I have written the generation code by myself.

How did you do it? Do you mind sharing the script?

**Comment by asimokby** [comment]
Hey there, 

I have written a script to do that. Check it out from [here](https://github.com/asimokby/GEC-M2Format-to-Sentence).

**Comment by asimokby** [comment]
Hey there, 

I have written a script to do that. Check it out from [here](https://github.com/asimokby/GEC-M2Format-to-Sentence).

**Comment by asimokby** [comment]
Hey there, 

I have written a script to do that. Check it out from [here](https://github.com/asimokby/GEC-M2Format-to-Sentence).
