### ISSUE TITLE
About speed up

### ISSUE THREAD

**Issue by Serenade-J** [chrisjbryant/errant#15]
Hi dear author, ERRANT is such an excellent tool and I'm very happy to see that the character level cost in the sentence alignment function is now computed by the much faster [python-Levenshtein] library instead of python's native `difflib.SequenceMatcher`, which makes ERRANT 3x faster.
I want to know if there are other potential explorations that can increase the speed. 
Can you give me some clues? Thank you very much!

**Comment by chrisjbryant** [comment]
Hey. I'm glad you like the speed-up. :)

The only other bottleneck is the custom word alignment function: `align` in alignment.py.
Unlike python-Levenshtein which only align strings, the `align` function is more complicated and aligns spacy Doc objects that contain lower case, lemma and pos information for each token. 

I did look at trying to cythonise it, but don't have much experience with cython so ultimately gave up. By all means take a look if you want to!
