### ISSUE TITLE
Errant incompatible with spacy 3

### ISSUE THREAD

**Issue by chrisjbryant** [chrisjbryant/errant#24]
Note to self: update errant to work with spacy 3.

**Comment by gunwook-datab** [comment]
when can we use this with spacy 3?

**Comment by chrisjbryant** [comment]
Honestly, probably not very soon. Spacy 3 changed quite a lot so it's not a trivial change. 
I'm also a bit hesitant anyway since I suspect spacy 3 will make errant slower again.

**Comment by gunwook-datab** [comment]
okay! thanks for your kindly comment!

**Comment by AntonOfTheWoods** [comment]
Did this get implemented by anyone?

**Comment by chrisjbryant** [comment]
There is an [unofficial PR](https://github.com/chrisjbryant/errant/pull/41) that does it, but I agree this is something I really need to get round to doing!

**Comment by AntonOfTheWoods** [comment]
Thanks @chrisjbryant , I did see that but was wondering why it didn't get merged after so much time. Is it just that you haven't had the bandwidth to stress test, or did you notice something deeper?

**Comment by chrisjbryant** [comment]
Yes, I just haven't had the time to test properly. I also have a list of other tweaks I want to add, so planned to do everything at once.

**Comment by dariush-saberi** [comment]
@chrisjbryant, I have implemented the changes you suggested in your [commit](#) and have pushed a repository to https://github.com/dariush-saberi/errant. It now works with spaCy 3 for my use case, and I thought it might be useful for others as well.

**Comment by chrisjbryant** [comment]
All this interest finally made me find time to do the update and test everything myself. ERRANT 3.0 with spacy 3.2<4 support now released!
