### ISSUE TITLE
Parallel_to_m2 is not working 

### ISSUE THREAD

**Issue by moodhiaj** [chrisjbryant/errant#33]
Hello Chris, I'm trying to convert my parallel dataset into m2 format so I used:
`import errant
! errant_parallel -orig D5-src.txt -cor D5-trg.txt -out /out_m2.m2`

and the output I got is: 
`Loading resources...
Processing parallel files...`

am I doing something wrong? 
Note: I am using Google Colab and my dataset is in Arabic language

**Comment by chrisjbryant** [comment]
Hiya,
ERRANT doesn't officially support Arabic, but is probably able to produce some semi-sensible output. 
The messages `Loading resources... Processing parallel files...` show that the script is running successfully and you can find the output in the path you specified after the `-out` flag.
