### ISSUE TITLE
Licensing concerns

### ISSUE THREAD

**Issue by zerogerc** [chrisjbryant/errant#34]
Hi, thanks for the awesome library.

Is there any way to remove `python-Levenshtein` from the dependencies? It's licensed under GPLv2 which is not compatible with MIT of errant.

**Comment by chrisjbryant** [comment]
This wasn't something I was aware of - thanks for letting me know!

I'll look into using an alternative, but in the meantime, you can try python's `difflib.SequenceMatcher` which is what ERRANT v2.1.0 relied on before `python-Levenshtein`.

**Comment by zerogerc** [comment]
Thanks a lot, I'll take look.

**Comment by chrisjbryant** [comment]
I should probably add that `difflib.SequenceMatcher` was ~3x slower than `python-Levenshtein` (which is why I changed it in the first place) so don't be surprised if you take a performance hit. At least it gets around the licensing issue though.

**Comment by chrisjbryant** [comment]
As a follow-up, I also found out that the [RapidFuzz](https://github.com/maxbachmann/RapidFuzz) package should be a good alternative (MIT license), which should also be faster than `python-Levenshtein` so I'll look at officially adding that at some point!

**Comment by chrisjbryant** [comment]
Just pushed ERRANT v2.3.1 which now uses RapidFuzz instead of `python-Levenshtein` so the licensing conflict is resolved!

**Comment by zerogerc** [comment]
Great news. Thanks a lot for the help!
