### ISSUE TITLE
Errant parse method not working

### ISSUE THREAD

**Issue by NourAlMerey** [chrisjbryant/errant#36]
I'm facing a problem with the parse method of errant. I know it uses the Spacy tagger and I have the English Spacy model ready so I'm not sure what might be the problem.
Thanks in advance
![Capture](https://user-images.githubusercontent.com/33783120/164319634-c15d52d9-830e-49cf-9e04-b2a972dd6506.PNG)

**Comment by chrisjbryant** [comment]
Sorry to hear you are having trouble. Can you tell me what command you are running exactly?

**Comment by NourAlMerey** [comment]
I'm using `edits = self._get_edits(orig, cor)`. Inside this method, you call the `self.annotator.parse(orig)` and that's what's causing the problem.
Many thanks for your reply

**Comment by chrisjbryant** [comment]
Can you give more information? E.g. what are you trying to do? There is no `_get_edits(orig, cor)` function in ERRANT, so I'm not sure what code you're running. :s

**Comment by NourAlMerey** [comment]
Oh, my bad. I'm sorry for miss explaining the problem. So I want to use Errant to get the edits happening on one string to produce the other (the first string being the incorrect sentence and the other being the correct one). To do that, I'm parsing the two strings using Errant and then doing an alignment by calling the align function. Finally, I'm calling the Errant merge function.

**Comment by NourAlMerey** [comment]
Problem Solved: I downgraded to a previous SpaCy version.
Many thanks
