### ISSUE TITLE
Wrong format for incorr_sentences.txt

### ISSUE THREAD

**Issue by Arvinth-s** [chrisjbryant/errant#37]
I used errant to preprocess the [Oscar Tamil](https://huggingface.co/datasets/oscar/viewer/unshuffled_deduplicated_ta/train) Dataset.

The source `m2` file looks like this.

```
S முன்னாள் ஜனாதிபதி மஹிந்த ராஜபக்ஷவினால் முன்னெடுக்கப்பட்ட போராட்டம் உட்பட வேலைநிறுத்த போராட்டங்களுக்கான நிதி அனுசரணையை சீனாவே வழங்கி நாட்டையும் அரசாங்கத்தையும் நெருக்கடிக்குள்ளாக்க முயல்கிறது என சமூக நலன்புரி பிரதி அமைச்சர் ரஞ்சன் ராமநாயக்க தெரிவித்தார்.
A 0 1|||R:OTHER|||முன்னாழ்|||REQUIRED|||-NONE-|||0
A 2 3|||R:OTHER|||மஹிண்த|||REQUIRED|||-NONE-|||0
A 7 8|||R:OTHER|||வேளைணிறுத்த|||REQUIRED|||-NONE-|||0
A 8 9|||R:NOUN|||போராட்டங்களுக்காண|||REQUIRED|||-NONE-|||0
A 9 10|||R:OTHER|||ணிதி|||REQUIRED|||-NONE-|||0
A 10 11|||R:NOUN|||அநுசரநையை|||REQUIRED|||-NONE-|||0
A 15 16|||R:NOUN|||ணெருக்கடிக்குல்ளாக்க|||REQUIRED|||-NONE-|||0
A 19 20|||R:OTHER|||ணலந்புரி|||REQUIRED|||-NONE-|||0
A 23 24|||R:NOUN|||ராமனாயக்க|||REQUIRED|||-NONE-|||0
A 24 25|||R:OTHER|||தெரிவித்தார்|||REQUIRED|||-NONE-|||0
```

The corresponding generated section of `corr_sentences.txt` looks like this.

```
S முன்னாள் ஜனாதிபதி மஹிந்த ராஜபக்ஷவினால் முன்னெடுக்கப்பட்ட போராட்டம் உட்பட வேலைநிறுத்த போராட்டங்களுக்கான நிதி அனுசரணையை சீனாவே வழங்கி நாட்டையும் அரசாங்கத்தையும் நெருக்கடிக்குள்ளாக்க முயல்கிறது என சமூக நலன்புரி பிரதி அமைச்சர் ரஞ்சன் ராமநாயக்க தெரிவித்தார்.
A 0 1|||R:OTHER|||முன்னாழ்|||REQUIRED|||-NONE-|||0
A 2 3|||R:OTHER|||மஹிண்த|||REQUIRED|||-NONE-|||0
A 7 8|||R:OTHER|||வேளைணிறுத்த|||REQUIRED|||-NONE-|||0
A 8 9|||R:NOUN|||போராட்டங்களுக்காண|||REQUIRED|||-NONE-|||0
A 9 10|||R:OTHER|||ணிதி|||REQUIRED|||-NONE-|||0
A 10 11|||R:NOUN|||அநுசரநையை|||REQUIRED|||-NONE-|||0
A 15 16|||R:NOUN|||ணெருக்கடிக்குல்ளாக்க|||REQUIRED|||-NONE-|||0
A 19 20|||R:OTHER|||ணலந்புரி|||REQUIRED|||-NONE-|||0
A 23 24|||R:NOUN|||ராமனாயக்க|||REQUIRED|||-NONE-|||0
A 24 25|||R:OTHER|||தெரிவித்தார்|||REQUIRED|||-NONE-|||0
```

The corresponding section of `incorr_sentences.txt` looks like this.

```
S முன்னாள் ஜனாதிபதி மஹிந்த ராஜபக்ஷவினால் முன்னெடுக்கப்பட்ட போராட்டம் உட்பட வேலைநிறுத்த போராட்டங்களுக்கான நிதி அனுசரணையை சீனாவே வழங்கி நாட்டையும் அரசாங்கத்தையும் நெருக்கடிக்குள்ளாக்க முயல்கிறது என சமூக நலன்புரி பிரதி அமைச்சர் ரஞ்சன் ராமநாயக்க தெரிவித்தார்.
0 1|||R:OTHER|||முன்னாழ்|||REQUIRED|||-NONE-|||0
A work 3|||R:OTHER|||மஹிண்த|||REQUIRED|||-NONE-|||0
7 8|||R:OTHER|||வேளைணிறுத்த|||REQUIRED|||-NONE-|||0
Badly do my 9|||R:NOUN|||போராட்டங்களுக்காண|||REQUIRED|||-NONE-|||0
9 10|||R:OTHER|||ணிதி|||REQUIRED|||-NONE-|||0
A English 10 11|||R:NOUN|||அநுசரநையை|||REQUIRED|||-NONE-|||0
up relatively 15 16|||R:NOUN|||ணெருக்கடிக்குல்ளாக்க|||REQUIRED|||-NONE-|||0
19 20|||R:OTHER|||ணலந்புரி|||REQUIRED|||-NONE-|||0
Change 23 24|||R:NOUN|||ராமனாயக்க|||REQUIRED|||-NONE-|||0
24 25|||R:OTHER|||தெரிவித்தார்|||REQUIRED|||-NONE-|||0
```

The first correction line doesn't start with `A`. The word `work` appears randomly after `A` in the second correction line. The corresponding sentence in the source file does not have the word `work`. Other lines also have similar patterns.

**Comment by chrisjbryant** [comment]
Hiya,

First off, ERRANT only officially supports English, so it might behave strangely with other languages (but should still do something reasonable).
Can you tell me what command you are running and what you are trying to do? 
ERRANT doesn't actually generate text anywhere so I can only think it's something wrong with your input or code.

**Comment by Arvinth-s** [comment]
Hey @chrisjbryant ,

Thanks for the quick reply. 

I ran the following commands
```
errant_parallel -orig path/to/original.txt -cor path/to/corrupted.txt  -out output/path/m2_format_source_file.txt
python ./error.py path/to/m2_format_source_file.txt  path/to/output_files
```
[path/to/output_files](https://drive.google.com/drive/folders/1bvhRoyEYDXTMSDHm1KHMEMXPav5kLATD?usp=sharing)
[m2_format_source_file](https://drive.google.com/file/d/1p5oxqx737ar-HszxSY3SRFl-iLbVdBCU/view?usp=sharing)
[original.txt](https://drive.google.com/file/d/1GhsTMFjbWvZc1nlP_SwsS9exUrm8LKvI/view?usp=sharing)
[corrupted.txt](https://drive.google.com/file/d/1DS3R9OB-qeHimJqChQ7EJxs1-uInSZ9h/view?usp=sharing)

**Comment by chrisjbryant** [comment]
> Thanks for the quick reply.

Np. :)

It looks like the problem is with the `error.py` script, but that's not an ERRANT script so I'm afraid I can't help!

**Comment by Arvinth-s** [comment]
> > Thanks for the quick reply.
> 
> Np. :)
> 
> It looks like the problem is with the `error.py` script, but that's not an ERRANT script so I'm afraid I can't help!

Thanks. I'll check with the other module.
