### ISSUE TITLE
Edit indices

### ISSUE THREAD

**Issue by jvhoffbauer** [chrisjbryant/errant#43]
What is the domain of [`Error.o_start`](https://github.com/chrisjbryant/errant/blob/master/errant/edit.py#L10), etc? Are they token indices within spaCy docs?

**Comment by chrisjbryant** [comment]
Yes. It's the token index for the edit within the original sentence. Edit.c_start is the same thing but for the offset in the corrected sentence.

**Comment by jvhoffbauer** [comment]
Thanks. Just to clarify - this assumes spaCy tokenisation or is it another method?

**Comment by chrisjbryant** [comment]
It makes no assumption at all.

If your text is untokenised, you can add a flag to make spacy do the tokenisation.
If your text is tokenised, you can split on whitespace and load the text as spacy Token objects directly.
