### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by AramTaravat** [chrisjbryant/errant#51]
Hello, Thanks for your work.
If I have two correct sentences for a wrong one, how can i convert it to m2 format? I mean with two annotator, each correct sentence as one annotator.

**Comment by chrisjbryant** [comment]
Check out the readme! There are instructions on how to do that using both the CLI and the API.

**Comment by AramTaravat** [comment]
I found this one :
errant_parallel -orig <orig_file> -cor <cor_file1> [<cor_file2> ...] -out <out_m2>
I think this mean that in [<cor_file2> ...] I should write other correct ones for that sentence . So for other sentences that have just one correction, what should we write in other files ? the correct sentence again or just an empty line?

**Comment by chrisjbryant** [comment]
Ah, so you have a different number of suggestions for each sentence?

In that case, you *could* repeat the correction from `<cor_file1>` in the other files and it won't affect anything, but I'd instead recommend using the API. Something like:

```
import errant

annotator = errant.load('en')

with open("output.m2", "w") as out:
    for orig in orig_sents:
        out.write("S "+orig) # Write the tokenised orig sentence in an m2 file (preceded by S)
        orig = annotator.parse(orig)
        for i, hyp in enumerate(hyp_sents):
            hyp = annotator.parse(hyp)
            edits = annotator.annotate(orig, hyp)
            # Write the edits for each hypothesis in M2 format
            for e in edits:
                out.write(e.to_m2(i)+"\n")
        # Empty line after each orig sentence in an m2 block
        out.write("\n")
```

**Comment by AramTaravat** [comment]
Yeah this works.
Also I tried the CLI and it worked, just it repeats the same lines of edits for sentences with one correction but with a little change it fixed.
Thank you
